name: daily-summary

# ① 07:30 (JST) = 22:30 (UTC) に毎日実行
on:
  schedule:
    - cron: '30 22 * * *'
  workflow_dispatch:   # 手動実行ボタンも有効化

permissions:
  contents: write      # Commit & push を許可

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      # 1. リポジトリをチェックアウト
      - uses: actions/checkout@v4

      # 2. Python 3.13 をセットアップ
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      # 3. 依存ライブラリをインストール
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install yfinance newsapi-python openai python-dotenv

      # 4. スクリプトを実行（キーは Secrets から渡す）
      - name: Fetch & summarise
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          NEWSAPI_KEY:    ${{ secrets.NEWSAPI_KEY }}
        run: |
          python fetch_fin_data.py         # JSON 生成
          python generate_summary.py       # 要約→CSV 追記

      # 5. 変更があればコミットしてプッシュ
      - name: Commit and push
        run: |
          git config user.name  "github-actions"
          git config user.email "github-actions@github.com"
          git add prompt_log.csv data_*.json
          git commit -m "chore: auto summary $(date '+%Y-%m-%d')" || echo "nothing to commit"
          git push

      # 6. Slack へ完了通知
      - name: Notify Slack
        if: success()
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "text": ":white_check_mark: *Daily summary 完了* :rocket:\nRun #${{ github.run_number }} (<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|詳細>)"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
